name: clean_demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #BLOC
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3

  # #Firebase
  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1
  firebase_auth: ^3.4.1
  firebase_storage: ^10.3.1
  firebase_messaging: ^11.4.4
  flutter_local_notifications: ^9.0.0
  #Generate
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  #HTTP
  http: ^0.13.4
  #Util
  equatable: ^2.0.3
  dartz: ^0.10.1
  intl: ^0.17.0
  #google font
  google_fonts: ^3.0.1
  #Sharedpreferences
  shared_preferences: ^2.0.15
  #snackbar
  top_snackbar_flutter: ^1.1.1
  #image picker
  image_picker: ^0.8.5+3
  #shimmer
  shimmer: ^2.0.0
dev_dependencies:
  # Testing
  mockito: ^5.2.0
  flutter_test:
    sdk: flutter
  #Lints
  flutter_lints: ^2.0.0
  # Intl
  flutter_intl: ^0.0.1
  intl_utils: ^2.6.1

  #Freezed
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  analyzer: ^3.4.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
flutter_intl:
  enabled: true
  class_name: Language
  main_locale: en
  arb_dir: resources/languages
  output_dir: lib/utils/languages